### PR TITLE
AXON-1817: Fix yaml.schemas and Setting sync conflicts

### LINKED ISSUE #155: yaml.schemas and Setting sync conflicts
**Describe the bug**
When use "Jira and Bitbucket" on different VSCodes of different system users System sync always output merge conflict in settings file, because of your "yaml.schemas" settings, which has absolute path to user's profile directory + version of extension.

**To Reproduce**
1. Setup for two different users VSCode with "Jira and Bitbucket"
2. Setup both VSCodes to same Microsoft account
3. Open first and sync settings
4. Open second and sync settings

**Expected behavior**
No problem sync

**Environment and Version (please complete the following information):**
 - Atlassian Plugin Version (3.4.11) 
 - Visual Studio Code Version (1.97.2) 
 - Is this a local or cloud environment? (Local) 
 - If Local, OS: Windows

**Additional context**
VSCode has variables for home directory: https://code.visualstudio.com/docs/editor/profiles#_common-questions
And version you can hide inside the json or make it handler more flexible.

### PR DESCRIPTION
**Pull request by om-ukr**
### What Is This Change?
Closes #155 

### How Has This Been Tested?

Basic checks:

- [X] `npm run lint`
- [X] `npm run test`

Advanced checks: 
- [X] If Atlassian employee & Bitbucket changes: did you test with DC in mind? [See Instructions](https://www.loom.com/share/71e5d17734a547f68fd6128be6cd760e?sid=835e58a7-1240-498d-b2d7-fa7fdf8ffa36)

Recommendations:
- [X] Update the CHANGELOG if making a user facing change

### CODE REVIEW

File: src/pipelines/yaml/pipelinesYamlHelper.ts [hunk 1]
```diff
@@ -29,14 +31,40 @@ async function addPipelinesSchemaToConfigAtScope(
...
+                // remove 'yaml.schemas' entirely
+                await workspace
+                    .getConfiguration()
+                    .update(YAML_SCHEMA_CONFIG_NAME_OF_VSCODE_YAML_EXTENSION, undefined, scope);
+            }
+        } catch (error) {
+            Logger.error(error, `Attempt to remove old 'yaml.schemas' configuration failed: ${error.message}`);
         }
-    });
-    newValue[key] = value;
```
Comment (BHulovatyi) [inline src/pipelines/yaml/pipelinesYamlHelper.ts:38]: You are deleting outdated entries, updating/removing the config, but you never add newValue[key] = value; as it was before. Is it expected?

Comment (om-ukr) [reply src/pipelines/yaml/pipelinesYamlHelper.ts:38]: Yes this is expected. 
PR is removing old approach with adding path to json schema to configuration. Instead we will relay on yamlPlugin.registerContributor [call](https://github.com/atlassian/atlascode/pull/1534/files#diff-07926156abcce11b95ee80abfd6a2614771d9c68031b26ba34b19f8c9a29efddR115).
So this part of code is going to make sure we remove old configuration in case it is exist in user config.
