### PR TITLE
Fix JQL registration issue in custom JQL panel

### LINKED ISSUE #260: Error viewing custom query
I have had two custom queries I used to view specific tasks I am working on. After the 3.4.20 update, when I try to view tickets under one of these, I get an error message:

Element with id {project}-2183_{hostname}_{hostname} is already registered

Where {project} is the Jira project name and {hostname} is my server name.

Custom queries:

assignee = currentUser() and status not in (Done, Canceled, Closed, Rejected, "On Hold") and type not in (Story)  ORDER BY key

assignee = currentUser() and resolution = Unresolved AND status not in (Canceled) AND type not in (Story) order by key

Also previous releases would show the number of tickets for each custom query and these counts no longer appear.

**To Reproduce**
1. Add these two custom queries (Possibly others)
2. Open Atlassian extension view
3. Click on one of the custom queries

**Expected behavior**
Expect to see Jira tickets matching custom query

**Screenshots**

Image

**Environment and Version (please complete the following information):**
 - Atlassian Plugin Version (3.4.20) 
 - Visual Studio Code Version (1.98.2) 
 - Is this a local or cloud environment? (Local) 
 - If Local, OS (windows)

### PR DESCRIPTION
**Pull request by marcomura**
### What Is This Change?

This fixes `Error viewing custom query` #260 .

This is a regression introduced in https://github.com/atlassian/atlascode/pull/252
as this bug was already fixed in https://github.com/atlassian/atlascode/pull/217

### How Has This Been Tested?

Basic checks:

- [X] `npm run lint`
- [X] `npm run test`

Advanced checks: 
- [ ] If Atlassian employee & Bitbucket changes: did you test with DC in mind? [See Instructions](https://www.loom.com/share/71e5d17734a547f68fd6128be6cd760e?sid=835e58a7-1240-498d-b2d7-fa7fdf8ffa36)

Recommendations:
- [X] Update the CHANGELOG if making a user facing change

### CODE REVIEW

File: src/views/jira/treeViews/utils.ts [hunk 1]
```diff
@@ -59,7 +59,7 @@ export class JiraIssueNode extends TreeItem {
             : TreeItemCollapsibleState.None;
         super(issue.key, collapsibleState);
 
-        this.id = `${issue.key}_${issue.siteDetails.id}_${issue.jqlSource.siteId}`;
+        this.id = `${issue.key}_${issue.siteDetails.id}_${issue.jqlSource.id}`;
```
Comment (sdzh-atlassian) [inline src/views/jira/treeViews/utils.ts:62]: Always the small things, eh?

**Review by sdzh-atlassian — APPROVED** [review]

File: src/views/jira/treeViews/utils.ts (hunk 1 above)
Comment (marcomura) [reply src/views/jira/treeViews/utils.ts:62]: yeah...
