### PR TITLE
AXON-591: fix save button is enabled without valid credentials

### LINKED ISSUE #560: Save site button disabled when attempting authentication with custom bitbucket URL
**Description**
The title

**To Reproduce**
1. Go to Atlassian Settings -> Bitbucket -> Authentication
2. Click Other Options
3. Start typing your custom bitbucket URL e.g. https://bitbucket.mycompany.org
4. No matter what happens after (fill in username/password, use personal access token, use custom SSL settings etc.) the Save Site button remains disabled.

**Expected behavior**
I would expect at least some more input as to why the button is disabled, or the button to be enabled as soon as I fill one of the authentication methods (username/password or access token)

**Screenshots**

Image

Image

**Environment and Version**
 - Atlassian Plugin Version (3.8.6) 
 - Visual Studio Code Version (1.102.0) 
 - Local Environment: Windows

### PR DESCRIPTION
**Pull request by apeni**
### What Is This Change?

This change fixes #560 .

Fix issue when the save button is enabled without valid credentials in the authentication dialog. And issue when the save button is disabled if there is an error in one of the tabs ( reason - the error state was not cleared when switching the tabs or from type, e.g from Jira Server to Jira Cloud ). 

**Changes that were made:**
- extracted existed constants, types and  helpers in AuthDialog to separate files
- add fields and errors clearing between tab switch and form type switch ( Jira Server -> Jira Cloud )
- add approproate fields and errors validation ( depending on tab or form type )
- add tests for existed and added helpers

**Steps to reproduce first issue:**
- Go to "Atlassian Settings"
- Click "Other options"
- Enter the `https://jiracloud.domain.com` as base url
- See that Save Button is enabled even with empty fields

**Steps to reproduce second issue:**
- Go to "Atlassian Settings"
- Click "Other options"
- Enter the `https://jiracloud.domain.com` as base url
- Click on username field and outside the field to see the error "uesrname is required"
- Got to "Personal Access Token" tab and enter the value for pat
- See that Save Button is disabled even when the value is entered 

**Screenrecord with current behaviour:**

https://github.com/user-attachments/assets/d6e3e01e-020a-4932-8f51-21b022182959

**Screenrecord with fixed behaviour:** 

https://github.com/user-attachments/assets/81272a3f-1e1f-4394-8c41-7913d9b0819d

### How Has This Been Tested?

Basic checks:

- [ ] `npm run lint`
- [ ] `npm run test`

Advanced checks: 
- [ ] If Atlassian employee & Bitbucket changes: did you test with DC in mind? [See Instructions](https://www.loom.com/share/71e5d17734a547f68fd6128be6cd760e?sid=835e58a7-1240-498d-b2d7-fa7fdf8ffa36)

Recommendations:
- [ ] Update the CHANGELOG if making a user facing change

### CODE REVIEW

File: src/react/atlascode/util/authFormUtils.ts [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+
+const isCheckBox = (element?: InputElement): element is HTMLInputElement => {
+    return !!element && element.type === 'checkbox';
+};
+
+export const isCheckboxOrRadio = (element?: InputElement): element is HTMLInputElement => {
+    return !!element && (element.type === 'checkbox' || element.type === 'radio');
+};
+
+export const getFieldValue = (field: FieldDescriptor): any => {
```
Comment (sspanchenko) [inline src/react/atlascode/util/authFormUtils.ts:29]: Would it be possible to replace "any" with a more specific type here? It could help improve type safety and make the return value clearer.

Comment (apeni) [reply src/react/atlascode/util/authFormUtils.ts:29]: Totally agree, but as these fuctions were just moved ( not added by me ) in utils to clear up the useFormValidation with some types and there are a lot of "any" in all of these methods/types, I think it should be a separate task to go throught the code and improve type safety.

**Review by sspanchenko — DISMISSED** [review]

**Review by marcomura — APPROVED** [review]
looks good, thanks!
