### PR TITLE
AXON-133: Comment on BB PR now work. Issue 212, 24 and BB Issue 762

### LINKED ISSUE #212: BitBucket comment gets corrupted if edited at all
**Describe the bug**

Image

**To Reproduce**
1. Write a comment on any file in a BitBucket Pull Request using the extension
2. Click Edit
3. Make any change to the comment (e.g. add some more text)
4. Original and edited contents are immediately lost and replaced with `[object Object]`
5. Attempting to edit the result also fails; the comment can only be fixed in a web browser with the original content recovered from a colleague's email record

**Expected behavior**
Edited comments should be saved faithfully

**Environment and Version (please complete the following information):**
 - Atlassian Plugin Version (3.4.13) 
 - Visual Studio Code Version (1.98.1) 
 - Is this a local or cloud environment? (Cloud?) 
 - If Cloud, Browser (chrome/Vivaldi)
 - If Local, OS (the extension is running in Linux)

### PR DESCRIPTION
**Pull request by bwieger-atlassian-com**
### What Is This Change?

Fixes #212 #24 
And BB Issue https://bitbucket.org/atlassianlabs/atlascode/issues/762/pr-comments-are-changed-to-object-object

### How Has This Been Tested?

Test on DC and Cloud 
See Loom: https://www.loom.com/share/3bd6debe9230489f91d3c27f1a3cec20

Basic checks:

- [x] `npm run lint`
- [x] `npm run test`

Advanced checks: 
- [x] If Atlassian employee & Bitbucket changes: did you test with DC in mind? [See Instructions](https://www.loom.com/share/71e5d17734a547f68fd6128be6cd760e?sid=835e58a7-1240-498d-b2d7-fa7fdf8ffa36)

**BEFORE (when editing a comment on a PR):** 
image

**AFTER** 
image

### CODE REVIEW

**Review by sdzh-atlassian — APPROVED** [review]
image

File: src/views/pullrequest/prCommentController.ts [hunk 1]
```diff
@@ -310,6 +310,16 @@ export class PullRequestCommentController implements vscode.Disposable {
...
     }
 
+    private extractCommentText(comment: PullRequestComment): string {
+        if (comment.body instanceof MarkdownString) {
+            return comment.body.value;
+        }
+        if (typeof comment.body === 'string') {
+            return comment.body;
+        }
+        throw new Error('Invalid comment body type');
```
Comment (marcomura) [inline src/views/pullrequest/prCommentController.ts:320]: what will happen when this Error is thrown? (aka, who is capturing it)

**Review by marcomura — APPROVED** [review]
left one comment about the new exception.
looks good otherwise!

File: src/views/pullrequest/prCommentController.ts (hunk 1 above)
Comment (bwieger-atlassian-com) [reply src/views/pullrequest/prCommentController.ts:320]: First, it is nearly impossible for this to happen. Just here in case. 

Yeah, it's not perfect when I test with it. 

The error will stop the API call from occurring, but the UI still "caches" the new comment so it looks like the comment was updated. 

Going to merge, but I'll spend 15 minutes seeing if there a simple pattern / fix
